"""create all tables

Revision ID: f89476c8173c
Revises: 
Create Date: 2025-10-26 21:32:44.814729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f89476c8173c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_files', sa.Integer(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_runs_id'), 'analysis_runs', ['id'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_run_id', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=True),
    sa.Column('md5', sa.String(length=32), nullable=True),
    sa.Column('sha1', sa.String(length=40), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_file_name'), 'files', ['file_name'], unique=False)
    op.create_index(op.f('ix_files_id'), 'files', ['id'], unique=False)
    op.create_index(op.f('ix_files_md5'), 'files', ['md5'], unique=False)
    op.create_index(op.f('ix_files_sha1'), 'files', ['sha1'], unique=False)
    op.create_index(op.f('ix_files_sha256'), 'files', ['sha256'], unique=False)
    op.create_table('classifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('classified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id')
    )
    op.create_index(op.f('ix_classifications_category'), 'classifications', ['category'], unique=False)
    op.create_index(op.f('ix_classifications_id'), 'classifications', ['id'], unique=False)
    op.create_table('features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('feature_name', sa.String(length=100), nullable=False),
    sa.Column('feature_value', sa.Text(), nullable=True),
    sa.Column('feature_type', sa.String(length=50), nullable=True),
    sa.Column('extracted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_features_feature_name'), 'features', ['feature_name'], unique=False)
    op.create_index(op.f('ix_features_id'), 'features', ['id'], unique=False)
    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('explanation', sa.JSON(), nullable=True),
    sa.Column('scored_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id')
    )
    op.create_index(op.f('ix_scores_id'), 'scores', ['id'], unique=False)
    op.create_index(op.f('ix_scores_risk_level'), 'scores', ['risk_level'], unique=False)
    op.create_index(op.f('ix_scores_score'), 'scores', ['score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scores_score'), table_name='scores')
    op.drop_index(op.f('ix_scores_risk_level'), table_name='scores')
    op.drop_index(op.f('ix_scores_id'), table_name='scores')
    op.drop_table('scores')
    op.drop_index(op.f('ix_features_id'), table_name='features')
    op.drop_index(op.f('ix_features_feature_name'), table_name='features')
    op.drop_table('features')
    op.drop_index(op.f('ix_classifications_id'), table_name='classifications')
    op.drop_index(op.f('ix_classifications_category'), table_name='classifications')
    op.drop_table('classifications')
    op.drop_index(op.f('ix_files_sha256'), table_name='files')
    op.drop_index(op.f('ix_files_sha1'), table_name='files')
    op.drop_index(op.f('ix_files_md5'), table_name='files')
    op.drop_index(op.f('ix_files_id'), table_name='files')
    op.drop_index(op.f('ix_files_file_name'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_analysis_runs_id'), table_name='analysis_runs')
    op.drop_table('analysis_runs')
    # ### end Alembic commands ###
